const data={
neighbor:["Angry Neighbor","😡","Someone is NOT happy about the noise.","Hey! It's your neighbor. We need to talk about what happened last night.",[["What did I do?","It was the noise! My windows were literally shaking."],["Uh... sorry?","Sorry isn't going to fix my picture frames!"],["I wasn't even home.","...Wait. You weren't? Then who was making the noise?"]]],
delivery:["Angry Delivery Driver","📦","A delivery has gone very, very wrong.","Hello! I'm the delivery driver. We have a little problem with your package.",[["What happened?","Your package somehow ended up in a swimming pool."],["Is it okay?","The package? Maybe. My shoes? Absolutely not."],["Can I get a refund?","Let's not get ahead of ourselves here."]]],
gamer:["Gaming Rival","🎮","Your online rival has something to say.","Yo! It's me. You really thought that last match was a win?",[["I destroyed you.","Destroyed me? You got lucky, bro."],["Run it back.","Finally! A rematch. Let's settle this."],["Who even are you?","THE GUY WHO BEAT YOU THREE TIMES."]]],
flirty:["Flirty Caller","💘","A suspiciously confident caller has your number.","Heyyy... I've been trying to get your attention all day.",[["Who is this?","Oh, you know exactly who this is... probably."],["How did you get my number?","That's a very good question. Next question!"],["Okay, what's up?","I just wanted to say... your profile picture is kinda cute."]]],
boss:["Angry Boss","👔","Your boss has questions about today.","We need to talk. I just looked at your work schedule.",[["What's wrong?","You put 'maybe' in the availability box."],["I'm on my way.","You're not scheduled today."],["Can this wait?","Unfortunately, your calendar says otherwise."]]],
stranger:["Mysterious Stranger","🕵️","A caller who knows WAY too much.","Hello. Don't hang up. I know this sounds strange, but I need to ask you something.",[["Who are you?","Let's just say... we've never met. Probably."],["I'm hanging up.","Wait! I haven't finished being mysterious yet."],["What do you want?","Your favorite snack. This is extremely important."]]],
friend:["Confused Friend","🤨","Your friend is calling with a completely wild story.","Bro... I think I accidentally signed us up for something.",[["For what?!","A competitive cheese rolling tournament."],["You did WHAT?","I panicked. The website had a very convincing button."],["I'm blocking you.","Fair. But we still have practice at 6."]]],
santa:["Santa","🎅","Santa has questions about your behavior.","Ho ho ho! We need to have a little chat about your place on the nice list.",[["I'm on the nice list.","Hmm. The elves have... notes."],["What did I do?","Let's just say the cookie jar incident was documented."],["Can I get a gift?","Negotiations are currently underway."]]]
};
let current="neighbor";
const grid=document.querySelector("#scenarioGrid"),name=document.querySelector("#callerName"),num=document.querySelector("#callerNumber");
Object.entries(data).forEach(([key,s])=>{let b=document.createElement("button");b.className="scenario"+(key===current?" active":"");b.innerHTML=`<span class="emoji">${s[1]}</span><strong>${s[0]}</strong><small>${s[2]}</small>`;b.onclick=()=>select(key);grid.appendChild(b)});
function select(k){current=k;let s=data[k];name.value=s[0];document.querySelectorAll(".scenario").forEach((b,i)=>b.classList.toggle("active",Object.keys(data)[i]===k))}
function openCall(){let s=data[current];document.querySelector("#modalName").textContent=name.value||s[0];document.querySelector("#modalNumber").textContent=num.value||"(555) 014-2026";document.querySelector("#avatar").textContent=s[1];document.querySelector("#actions").classList.remove("hidden");document.querySelector("#conversation").classList.add("hidden");document.querySelector("#status").textContent="Incoming Call";document.querySelector("#modal").classList.remove("hidden")}
function closeCall(){document.querySelector("#modal").classList.add("hidden")}
document.querySelector("#start").onclick=()=>document.querySelector("#scenarios").scrollIntoView({behavior:"smooth"});
document.querySelector("#preview").onclick=openCall;
document.querySelector("#decline").onclick=()=>{document.querySelector("#status").textContent="Call Declined";setTimeout(closeCall,500)};
document.querySelector("#answer").onclick=()=>{let s=data[current];document.querySelector("#actions").classList.add("hidden");document.querySelector("#conversation").classList.remove("hidden");document.querySelector("#status").textContent="Connected";document.querySelector("#dialogue").textContent=s[3];let box=document.querySelector("#choices");box.innerHTML="";s[4].forEach(x=>{let b=document.createElement("button");b.className="choice";b.textContent=x[0];b.onclick=()=>document.querySelector("#dialogue").textContent=x[1];box.appendChild(b)})};
document.querySelector("#end").onclick=()=>{document.querySelector("#status").textContent="Call Ended";setTimeout(closeCall,450)};
document.querySelector("#close").onclick=closeCall;
document.querySelector("#modal").onclick=e=>{if(e.target.id==="modal")closeCall()};